### ISSUE TITLE
Project Still be worked?

### ISSUE THREAD

**Issue by DanitiKain** [timegridio/timegrid#188]
I have some questions and was wondering if this project still exists I have a great idea to take this next level. I have tried every calendar solution I can find and not one offers what I need.

**Comment by guifelix** [comment]
It's written on readme: 
> This project will become unsupported by 01/01/2018. If you require further information, please contact the author

So I believe if you want to make any modification, you'll have to make a fork.

**Comment by alariva** [comment]
Hi @DanitiKain , I'm unable to continue working on this project due to priorities. I'm planning, though, to re-write an appointment package from scratch which I might be needing at some point in the future to integrate with ongoing projects. Feel free to fork or take any useful piece that you may need, I'm happy to help on some specifics if you require. Thanks for asking, best regards.

**Comment by boghy933** [comment]
Hi @alariva!

I work for a web agency, we are interested in an appointment system for car services.

We were wondering if you have you already re-written your appointment package, and if you would be willing to apply customizations, obviously for a fee.

If you are interested, please feel free to contact me at alex.bostan@idearia.it.

Thank you,
Alex

**Comment by alariva** [comment]
Hi @boghy933 ,

Thanks for your inquiry, feel free to drop me an email so we discuss on how could I help you.

Best regards,

**Comment by alariva** [comment]
Hi everyone, thanks for reaching out!

Development is back :)
