### ISSUE TITLE
Bug: Cannot pick a time for appointment

### ISSUE THREAD

**Issue by annylinh08** [timegridio/timegrid#196]
Hi there, I have created a business with Toronto timezone, and set with all availability for the staff but when I book appointment, I could not pick a time to. Is there anyone know how to fix this problem?
![image](https://user-images.githubusercontent.com/47993207/75799112-93adf800-5d45-11ea-81e3-dbdd81ad4157.png)
![image](https://user-images.githubusercontent.com/47993207/75799330-f7382580-5d45-11ea-82c2-363779de88b8.png)
![image](https://user-images.githubusercontent.com/47993207/75799596-4b430a00-5d46-11ea-86fd-9ce29974bd2d.png)

**Comment by alariva** [comment]
Hi @annylinh08 ,

In your second screenshot, the time *from* is `8:00 AM` and *to* is `12:00 AM`, that means that the time range is invalid (the *to* field is in the past).

*WORKAROUND:* Try setting again availability by putting *from* => `8:00 AM` and *to* => `12:00 PM`
---
This is, however, a bug spotted since Timegrid should have displayed `12:00 PM` as default, so we are going to fix it.

**Comment by alariva** [comment]
@annylinh08 Fix is in progress: https://youtu.be/QbfFdZ0y4Qk
