### ISSUE TITLE
Support for PHP 7.4

### ISSUE THREAD

**Issue by asm0dey** [timegridio/timegrid#203]
### Prerequisites

* [x] Are you running the latest version ?
* [x] Are you reporting to the correct repository ?
* [x] Did you perform a search ?

### Description

I have PHP 7.4 on my hosting, but timegrid depends on packages, which are incompatible with PHP 7.4. Is i possible to provide support for latest version of PHP?

**Comment by LoveDuckie** [comment]
@asm0dey I'm not a maintainer of this project, but have you considered the Docker image [that they have available in the repository?](https://github.com/timegridio/dockerfiles/blob/master/Dockerfile).

I imagine that it largely depends on what kind of hosting you have currently, but if you have root access to the machine that you are deploying then it could be suitable.

**Comment by asm0dey** [comment]
@LoveDuckie thanks for idea but I would prefer to stick with the latest version of PHP — fewer chances of security issues, better performance and so on…

**Comment by alariva** [comment]
Thanks for the request.
I'm no longer maintaining this project due to personal priorities, but leaving the source code up for anyone willing to explore it and play around with it. Unfortunately bumping the PHP version needs to be accompanied with a series of dependency packages and code updates, which is quite a large change as of today. If you need to play around with the application the best approach here is probably setting up a docker container.

**Comment by asm0dey** [comment]
@alariva Thank you for update. Could you please announce stop of maintenance in the README?
